sudo: false
cache:
  directories:
    - "node_modules"
notifications:
  email:
    on_failure: always
    on_success: never
language: node_js
node_js:
  - "8"
before_install: npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
